create database SirketVeritabani
go
use SirketVeritabani

create table BIRIM(
ID INT IDENTITY(1,1) PRIMARY KEY,
BIRIM_AD NVARCHAR(50)
)
GO
INSERT INTO BIRIM (BIRIM_AD) VALUES ('KALİTE'),('İDARİ'),('ARGE'),('TEKNİK');

create table UNVAN(
ID INT IDENTITY(1,1) PRIMARY KEY,
UNVAN_AD NVARCHAR(50)
)
INSERT INTO unvan VALUES ('MÜHENDİS'),('İK UZMANI'),('TEKNİSYEN');

create table IL(
ILID CHAR(2) PRIMARY KEY,
IL_AD VARCHAR(30) UNIQUE NOT NULL
)
INSERT INTO IL VALUES ('06','ANKARA'),('34','İSTANBUL'),('35','İZMİR');

CREATE TABLE ILCE(
ILCEID INT IDENTITY(1,1) PRIMARY KEY,
ILCE_AD VARCHAR(30) NOT NULL,
ILID CHAR(2) NOT NULL REFERENCES IL(ILID),
CONSTRAINT ILCETEKIL UNIQUE (ILCE_AD,ILID))

INSERT INTO ilce VALUES 
('ÇANKAYA','06'),('POLATLI','06'),('YENİMAHALLE','06'),('AVCILAR','34'),
('BEYLİKDÜZÜ','34'),('ESENYURT','34'),('BUCA','35'),('KARŞIYAKA','35'),('KONAK','35');


CREATE TABLE proje (
proje_no INT IDENTITY(1,1) PRIMARY KEY,
proje_ad VARCHAR(20) UNIQUE NOT NULL,
baslama_tarihi DATE NOT NULL,
planlanan_bitis_tarihi DATE NOT NULL
);

INSERT INTO proje VALUES
('TEMİZ DÜNYA','2015.01.20','2017.01.11'),
('GÜVENLİ INTERNET','2017.05.15','2020.06.09'),
('MUTLU ŞEHİR','2017.07.11','2019.11.29'),
('AKILLI EVLER','2018.02.10','2021.11.29'),
('SESSİZ ORTAM','2018.03.01','2019.11.29');