create database SirketVeritabani
go
use SirketVeritabani

create table BIRIM(
ID INT IDENTITY(1,1) PRIMARY KEY,
BIRIM_AD NVARCHAR(50)
)
GO
INSERT INTO BIRIM (BIRIM_AD) VALUES ('KALİTE'),('İDARİ'),('ARGE'),('TEKNİK');

create table UNVAN(
ID INT IDENTITY(1,1) PRIMARY KEY,
UNVAN_AD NVARCHAR(50)
)
INSERT INTO unvan VALUES ('MÜHENDİS'),('İK UZMANI'),('TEKNİSYEN');

create table IL(
ILID CHAR(2) PRIMARY KEY,
IL_AD VARCHAR(30) UNIQUE NOT NULL
)
INSERT INTO IL VALUES ('06','ANKARA'),('34','İSTANBUL'),('35','İZMİR');

CREATE TABLE ILCE(
ILCEID INT IDENTITY(1,1) PRIMARY KEY,
ILCE_AD VARCHAR(30) NOT NULL,
ILID CHAR(2) NOT NULL REFERENCES IL(ILID),
CONSTRAINT ILCETEKIL UNIQUE (ILCE_AD,ILID))

INSERT INTO ilce VALUES 
('ÇANKAYA','06'),('POLATLI','06'),('YENİMAHALLE','06'),('AVCILAR','34'),
('BEYLİKDÜZÜ','34'),('ESENYURT','34'),('BUCA','35'),('KARŞIYAKA','35'),('KONAK','35');